sudo: required
dist: trusty
language: bash

script:

- sudo apt-get install pastebinit libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev build-essential libgmp-dev zlib1g-dev -y
- git clone https://github.com/wpscanteam/wpscan.git
- cd wpscan
- sudo sudo gem install bundler && bundle install --without test development
- yes | ruby wpscan.rb $site | tee strona.txt 
- pastebinit strona.txt
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

